# Generated by Django 5.1.3 on 2024-11-16 20:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id_customer', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.CharField(max_length=25)),
                ('occupation', models.CharField(max_length=55)),
                ('birth', models.DateField(auto_now_add=True)),
                ('income', models.FloatField()),
                ('sale_date', models.DateField(auto_now_add=True)),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
