# Generated by Django 5.1.3 on 2024-11-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customer_email_customer_phone_customer_service_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.BooleanField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, default=False, max_length=35),
        ),
    ]
