# Generated by Django 5.1.3 on 2024-11-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customer_gender_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.BooleanField(blank=True, default='M'),
        ),
    ]
