# Generated by Django 5.1.3 on 2024-11-16 20:01

import employee.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id_employee', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_code', models.CharField(max_length=25)),
                ('business_unity', models.CharField(max_length=25)),
                ('function', models.CharField(max_length=25)),
                ('birth', models.DateField(auto_now_add=True)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=employee.models.upload_image_employee)),
            ],
        ),
    ]
