# Generated by Django 5.1.3 on 2024-11-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_birth_alter_employee_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.BooleanField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(blank=True, default=False, max_length=35),
        ),
    ]
