# Generated by Django 5.1.3 on 2024-11-16 19:29

import car.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id_car', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=55)),
                ('model', models.CharField(max_length=55)),
                ('fuel', models.CharField(max_length=55)),
                ('type', models.CharField(max_length=55)),
                ('release_year', models.DateField()),
                ('state', models.CharField(max_length=15)),
                ('quilometers', models.IntegerField()),
                ('publishing_company', models.CharField(max_length=55)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=car.models.upload_image_car)),
            ],
        ),
    ]
