# Generated by Django 5.1.3 on 2024-11-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
